### ISSUE TITLE
Read error: #<NoMethodError: undefined method `reopen' for "-":String>

### ISSUE THREAD

**Issue by ghost** [fringd/zipline#6]
I'm following the example in the readme, I am calling zipline in my controller action like this:

``` ruby
  include ActionController::Streaming
  include Zipline

  def download_many
    recordings_params = params[:recordings]
    files = recordings_params[:paths].map{|p| [open(full_path(p)), File.basename(p)]}
    logger.info open(full_path recordings_params[:paths][0]).size
    logger.info "zipline(#{files}, #{recordings_params[:filename]})"
    zipline(files, recordings_params[:filename])
  end
```

The log shows this:

```
22822774
zipline([[#<File:/Users/hackeron/Development/Xanview/xanAgent/data/xanview/xanboxid1/internal/52ab35a548616311d3360000/20140316_17/20140316_172858_to_172957.mp4>, "20140316_172858_to_172957.mp4"], [#<File:/Users/hackeron/Development/Xanview/xanAgent/data/xanview/xanboxid1/internal/52ab35a548616311d3360000/20140316_17/20140316_172756_to_172858.mp4>, "20140316_172756_to_172858.mp4"]], test.zip)
2014-03-20 09:44:50 +0000: Read error: #<NoMethodError: undefined method `reopen' for "-":String>
/usr/local/Cellar/ruby/2.1.1/lib/ruby/gems/2.1.0/gems/rubyzip-1.1.2/lib/zip/output_stream.rb:32:in `initialize'
/usr/local/Cellar/ruby/2.1.1/lib/ruby/gems/2.1.0/gems/zipline-0.0.6/lib/zipline/output_stream.rb:9:in `initialize'
/usr/local/Cellar/ruby/2.1.1/lib/ruby/gems/2.1.0/gems/rubyzip-1.1.2/lib/zip/output_stream.rb:51:in `new'
/usr/local/Cellar/ruby/2.1.1/lib/ruby/gems/2.1.0/gems/rubyzip-1.1.2/lib/zip/output_stream.rb:51:in `open'
/usr/local/Cellar/ruby/2.1.1/lib/ruby/gems/2.1.0/gems/zipline-0.0.6/lib/zipline/zip_generator.rb:18:in `each'
/usr/local/Cellar/ruby/2.1.1/lib/ruby/gems/2.1.0/gems/actionpack-4.0.4/lib/action_dispatch/http/response.rb:83:in `each'
/usr/local/Cellar/ruby/2.1.1/lib/ruby/gems/2.1.0/gems/actionpack-4.0.4/lib/action_dispatch/http/response.rb:42:in `each'
/usr/local/Cellar/ruby/2.1.1/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/body_proxy.rb:31:in `each'
/usr/local/Cellar/ruby/2.1.1/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/body_proxy.rb:31:in `each'
/usr/local/Cellar/ruby/2.1.1/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/body_proxy.rb:31:in `each'
/usr/local/Cellar/ruby/2.1.1/lib/ruby/gems/2.1.0/gems/puma-2.8.1/lib/puma/server.rb:615:in `handle_request'
/usr/local/Cellar/ruby/2.1.1/lib/ruby/gems/2.1.0/gems/puma-2.8.1/lib/puma/server.rb:361:in `process_client'
/usr/local/Cellar/ruby/2.1.1/lib/ruby/gems/2.1.0/gems/puma-2.8.1/lib/puma/server.rb:254:in `block in run'
/usr/local/Cellar/ruby/2.1.1/lib/ruby/gems/2.1.0/gems/puma-2.8.1/lib/puma/thread_pool.rb:92:in `call'
/usr/local/Cellar/ruby/2.1.1/lib/ruby/gems/2.1.0/gems/puma-2.8.1/lib/puma/thread_pool.rb:92:in `block in spawn_thread'
```

Any ideas?

I'm using these versions: zipline (0.0.6), rubyzip (1.1.2), rails (4.0.4)

**Comment by yanismydj** [comment]
Having the same problem myself.  I guess this is closed due to inactivity but this problem still occurs with Rails 4 and zipline 0.0.6

**Comment by yanismydj** [comment]
Nevermind -- I was using an older version and solved it by using the latest from github instead of the latest from rubygems.  I would suggest updating the version on rubygems to the latest!
